name: mypostgres
services:
    postgres:
        container_name: mypostgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=mydb
              # - TZ=Asia/Kolkata
              # - PGTZ=Asia/Kolkata
        ports:
            - 5432:5432
        image: postgres:16
